# Konfiguration für Upptime (GitHub Pages, ohne eigene Domain)
owner: dimideveloper
repo: paylock-status

sites:
  - name: PayLock Website
    url: https://paylock.eu

status-website:
  baseUrl: /paylock-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PayLock Status
  introTitle: "**PayLock** Status Monitoring"
  introMessage: Willkommen auf der Statusseite von **PayLock**. Hier siehst du in Echtzeit, ob unsere Dienste online sind.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dimideveloper/paylock-status
